### ISSUE TITLE
[🐞]tailwindcss v4 doesn't load in v1.13.0

### ISSUE THREAD

**Issue by hollandjake** [QwikDev/qwik#7478]
### Which component is affected?

Qwik Runtime

### Describe the bug

When using tailwind v4 and its corresponding plugin `@tailwindcss/vite` 

- In version v1.12.1 it loads correctly in both dev and preview/prod
- In version v1.13.0 it does not load any global.css

Not sure on which commit is the cause

### Reproduction

n/a

### Steps to reproduce

- `bun create qwik@latest empty ./test --i`
- `cd test`
- `bun qwik add tailwind`
- `bun run dev`

Opening the index page in a browser you will notice no global.css file has been included.
Manually downgrading `@builder.io/qwik` to `1.12.1` allows styles to be re-included

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M2 Pro
    Memory: 109.06 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 23.7.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.9.2 - /opt/homebrew/bin/npm
    pnpm: 9.15.2 - ~/Library/pnpm/pnpm
    bun: 1.2.8 - /opt/homebrew/bin/bun
  Browsers:
    Brave Browser: 132.1.74.48
    Chrome: 134.0.6998.166
    Safari: 17.5
  npmPackages:
    @builder.io/qwik: 1.12.1 => 1.12.1 
    @builder.io/qwik-city: 1.12.1 => 1.12.1 
    typescript: ^5.8.2 => 5.8.2 
    undici: ^7.7.0 => 7.7.0 
    vite: ^5.4.16 => 5.4.16
```

**Comment by Paulzalele** [comment]
Came across the same issue, had to downgrade to 1.12.1 to fix it.

**Comment by hollandjake** [comment]
@Paulzalele this has now been fixed in the latest version of @tailwindcss/vite (4.1.2). apologies for not closing the issue

**Comment by Paulzalele** [comment]
Somehow it's not fixed on my end with Tailwind 4.1.2 or 4.1.3, I have to downgrade Qwik to 1.12.1 for it to work.
