### ISSUE TITLE
[🐞] SSG disables SPA navigation

### ISSUE THREAD

**Issue by wmertens** [QwikDev/qwik#7749]
### Which component is affected?

Qwik Runtime

### Describe the bug

SSG should just be like a pre-cached SSR, but when visiting SSG pages, Link does not cause SPA navigation.

### Reproduction

https://qwikdev-v2-router-things.qwik-8nx.pages.dev/ecosystem/

### System Info

```shell
v2 but probably v1 too
```

**Comment by lbensaad** [comment]
For me, using SSG, clicking on Links is working,  but for example:
```
const nav = useNavigate();
nav('/orders/view/?id=123');
```
it opens the page `/orders/view/` but without the id param, it is lost.
This happens only in `v1.15.0`,  when I switch back to `v1.14.1` it works normal, and the id param is prserved

**Comment by wmertens** [comment]
@lbensaad are you sure? I didn't think anything changed in v1.15 that would cause that. 
Do you have a proxy in front of your Qwik app? Could it be that it ignores search parameters when looking for static files?

**Comment by lbensaad** [comment]
Yes @wmertens , just confirmed with a new empty project and added static adapter for SSG.
In `routes` I created a new folder `test` with some `index.tsx`. Then added button in `routes/index.tsx` to navigate to `/test/?id=123`. 
Using `pnpm dev` works fine and it goes to `/test/?id=123` but when I run `pnpm build` then serve the dist folder with `http-server dist` and click on the button it goes to `/test/`, it drops the id parameter!. However clicking `<Link href="/test/?id=123">`  works as expected and keeps the parameter.

When I downgrade to `v1.14.1`, then build and serve, clicking the button works as expected and goes to  `/test/?id=123`.


Here is my `routes/index.tsx`:

```
import { component$ } from '@builder.io/qwik';
import { useNavigate, type DocumentHead, Link } from '@builder.io/qwik-city';

export default component$(() => {
  const nav = useNavigate();
  return (
    <>
      <h1>Hi 👋</h1>
      <div>
        Can't wait to see what you build with qwik!
        <br />
        <button
          onClick$={() => {
            nav('/test?id=123');
          }}
        >
          Nav To Test
        </button>
        <Link href="/test?id=123">Link to test</Link>
      </div>
    </>
  );
});

export const head: DocumentHead = {
  title: 'Welcome to Qwik',
  meta: [
    {
      name: 'description',
      content: 'Qwik site description',
    },
  ],
};

```

**Comment by lbensaad** [comment]
I just tried to update my PWA SPA SSG project to v2 because of issue #7627 but now I am stuck with this one, nav(url) is not working. any way around? or when this will be fixed? 
Thanks

**Comment by gioboa** [comment]
I tested the provided snippet with the latest v1 release and it's working fine in `dev` and `preview`. v2 is working fine too btw.
So I'm closing this issue for now, feel free to re-open it if it's still an issue for you. Thanks.

**Comment by lbensaad** [comment]
yes it works with dev but not after build, and the title says SSG, did you try with the static adapter

**Comment by gioboa** [comment]
I tried with SSG and preview and the latest v1 worked fine. 🤔

**Comment by lbensaad** [comment]
The bug happens only when you serve static html files using a webserver, like nginx or http-server.

**Comment by n9** [comment]
@gioboa Could you please reopen this issue? I've just tested with v2.0.0-beta.9 and in SSG the SPA navigation does not occur.

When you click a link, it does a "full" navigation instead of the SPA navigation.

![Image](https://github.com/user-attachments/assets/67c68453-7038-4c2a-b38e-3c546d1a1c9e)

**Comment by n9** [comment]
@wmertens Do you know if it's a simple fix or it will require a deep architectural change?

**Comment by wmertens** [comment]
@n9 no idea but probably simple. For some reason the SSG causes the Link to always decide to do MPA.

**Comment by wmertens** [comment]
This is fixed in #8101 thanks to #8097 plus some fixes

**Comment by lbensaad** [comment]
> For me, using SSG, clicking on Links is working, but for example:
> 
> ```
> const nav = useNavigate();
> nav('/orders/view/?id=123');
> ```
> 
> it opens the page `/orders/view/` but without the id param, it is lost. This happens only in `v1.15.0`, when I switch back to `v1.14.1` it works normal, and the id param is prserved

This is still broken in lastest V1.17.2 with ssg static adapter. When it will be solved?
